### ISSUE TITLE
bug: diff not possible if left dict is empty

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/pan-os-upgrade-assurance#1]
see [this line](https://github.com/PaloAltoNetworks/vmseries-upgrades-tests/blob/003fe9fb5ceda60c24667487b1fdb9447effcea3/upgrade_readiness/src/upgrade_readiness/snapshot_compare.py#L376)

suggested approach:

* when both dicts are empty just return empty results
* when no common keys is there:
  * try to check if we at the lowest level by checking a type of a dict element from left or right side, whichever works:
    * `yes` - raise error, it looks like we are comparing to different data types
    * `no` - common keys are used only to go down one level here, simply return an empty set so that the loop that loop based on `keys_to_check` ends

**Comment by alperenkose** [comment]
Merged with #77
