### ISSUE TITLE
Error when build container images

### ISSUE THREAD

**Issue by sakkarinpic** [PaloAltoNetworks/pan-os-upgrade-assurance#61]
I was using your build.sh and Docker file in my environment and run build.sh but, I found error

======================================================================
Building the image under the default name: panos_upgrade_assurance
Building panos-upgrade-assurance (0.0.1)

/root/panos_upgrade_assurance does not contain any element
cp: cannot stat '../dist/panos_upgrade_assurance*': No such file or directory
[+] Building 7.7s (10/11)                                                                                                                                     
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 341B                                                                                                                     0.0s
 => [internal] load metadata for docker.io/library/python:3.10                                                                                           1.0s
 => [1/8] FROM docker.io/library/python:3.10@sha256:0da028d058c56277dc3e5f197bcdc53ffe2dd5c6cd947b48747c8a8d24911be4                                     0.0s
 => [internal] load build context                                                                                                                        0.5s
 => => transferring context: 340B                                                                                                                        0.5s
 => CACHED [2/8] WORKDIR /tmp/prereqs                                                                                                                    0.0s
 => [3/8] COPY files/requirements.txt ./                                                                                                                 0.1s
 => [4/8] COPY files/panos_upgrade_assurance* ./                                                                                                         0.0s
 => [5/8] RUN python -m pip install -r requirements.txt                                                                                                  5.0s
 => ERROR [6/8] RUN python -m pip install panos_upgrade_assurance*.tar.gz                                                                                1.1s 
------                                                                                                                                                        
 > [6/8] RUN python -m pip install panos_upgrade_assurance*.tar.gz:                                                                                           
#0 0.891 WARNING: Requirement 'panos_upgrade_assurance*.tar.gz' looks like a filename, but the file does not exist                                            
#0 0.919 Processing ./panos_upgrade_assurance*.tar.gz                                                                                                         
#0 0.954 ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/tmp/prereqs/panos_upgrade_assurance*.tar.gz'
======================================================================

I don't sure the file "panos_upgrade_assurance*.tar.gz" was create on build.sh right? how to fix issue from this error?

Building panos-upgrade-assurance (0.0.1)

/root/panos_upgrade_assurance does not contain any element
cp: cannot stat '../dist/panos_upgrade_assurance*': No such file or directory

BR
Sakkarin Pichetskul

**Comment by sakkarinpic** [comment]
issue was not resolved, I cannot create docker images for using from Cortex XSOAR.

**Comment by FoSix** [comment]
@sakkarinpic : I've re-opened this issue and we'll take a look at it. Stay tuned!

**Comment by sakkarinpic** [comment]
Hi FoSix,

I was resolved this issue by change the build.sh to below

#!/bin/bash

if [ "$IMAGE_PREFIX" ]; then 
  echo "Building the image under the custom name: ${IMAGE_PREFIX}"
else
  echo "Building the image under the default name: panos_upgrade_assurance"
fi

DIST_PREFIX=panos_upgrade_assurance
IMAGE_PREFIX="${IMAGE_PREFIX:-panos_upgrade_assurance}" 
TEMP_FILES=files

if [ -d ${TEMP_FILES} ]; then rm -f ${TEMP_FILES}/*
else mkdir ${TEMP_FILES}
fi

# generate requirements.txt file 
poetry export --without-hashes --format=requirements.txt > ${TEMP_FILES}/requirements.txt

# build the latest libraries
rm -f ../dist/${DIST_PREFIX}*
poetry build

# copy over the built package
cp ./dist/${DIST_PREFIX}* ./${TEMP_FILES}


And the step for create docker images is below.

1. Download all files from repo to your directory
git clone https://github.com/PaloAltoNetworks/pan-os-upgrade-assurance.git
2. go to directory path
cd pan-os-upgrade-assurance/docker_image
3. move all file to directory path /pan-os-upgrade-assurance/
mv Dockerfile ./pan-os-upgrade-assurance/
mv build.sh ./pan-os-upgrade-assurance/
4. chmod +x build.sh
5. change some details in file build.sh
nano build.sh
and change cp ../dist/${DIST_PREFIX}* ./${TEMP_FILES} to cp ./dist/${DIST_PREFIX}* ./${TEMP_FILES}
Ctrl + x and Y
6. ./build.sh

**Comment by sakkarinpic** [comment]
Hi FoSix,

I was resolved this issue by change the build.sh to below

#!/bin/bash

if [ "$IMAGE_PREFIX" ]; then 
  echo "Building the image under the custom name: ${IMAGE_PREFIX}"
else
  echo "Building the image under the default name: panos_upgrade_assurance"
fi

DIST_PREFIX=panos_upgrade_assurance
IMAGE_PREFIX="${IMAGE_PREFIX:-panos_upgrade_assurance}" 
TEMP_FILES=files

if [ -d ${TEMP_FILES} ]; then rm -f ${TEMP_FILES}/*
else mkdir ${TEMP_FILES}
fi

# generate requirements.txt file 
poetry export --without-hashes --format=requirements.txt > ${TEMP_FILES}/requirements.txt

# build the latest libraries
rm -f ../dist/${DIST_PREFIX}*
poetry build

# copy over the built package
cp ./dist/${DIST_PREFIX}* ./${TEMP_FILES}

And the step for create docker images is below.

1. Download all files from repo to your directory
git clone https://github.com/PaloAltoNetworks/pan-os-upgrade-assurance.git
2. go to directory path
cd pan-os-upgrade-assurance/docker_image
3. move all file to directory path /pan-os-upgrade-assurance/
mv Dockerfile ./pan-os-upgrade-assurance/
mv build.sh ./pan-os-upgrade-assurance/
4. chmod +x build.sh
5. change some details in file build.sh
nano build.sh
and change cp ../dist/${DIST_PREFIX}* ./${TEMP_FILES} to cp ./dist/${DIST_PREFIX}* ./${TEMP_FILES}
Ctrl + x and Y
6. ./build.sh

**Comment by sakkarinpic** [comment]
Hi FoSix,

Thanks for your update.
I just need explain how to build images for someone will not understand what the issue were happened from that I found.
Because from your script may need describe some pre-required for install package and the step to build the images.

And the step for using in the Cortex XSOAR and sample playbook .yml file.

BR
