### ISSUE TITLE
should we check for scheduled jobs as a precheck

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/pan-os-upgrade-assurance#76]
Doing an upgrade installation during a scheduled update (content DB, etc) can cause the upgrade to fail. This can be problematic when doing the upgrades automatically. 
Is this a candidate for a check?

**Comment by adambaumeister** [comment]
I think this is a good idea, you should be able to use `show jobs` to determine it.

**Comment by FoSix** [comment]
let's do two tests:
- `check_jobs` - run `show jobs`
- `check_schedules` - check for any scheduled installations in the config, optional parameter with a time frame

**Comment by FoSix** [comment]
Closing this issue in favour of two others representing both checks:
- #87
